pipeline {
	agent {
		node {
			label 'QA'
		}
	}
stages {
	  stage ('copy-war'){
		   steps {
			    script {
			         sh 'aws s3 cp s3://war-file-bucket1/WebApp.war /mnt/web-server/apache-tomat-9.0.89/webapps'
          }
       }
    }
	
}
	 
}
    
